#!/usr/bin/env python3
"""Build the card-face scanner preview (cards_v3.html + cardface-assets.js).

Takes the LIVE cards.html and rewires filters and card entries into the
card-face design proven in mockups/trait-icons-poc.html:
- rulebook chips for trait + suit filters (medallion/glyph, solid color,
  black-text active state), capsule outlines elsewhere
- entries: name + suit banners (suit glyph), skill banner icons, vertical
  trait pills with medallions (sorted shortest first, kissing overlap),
  true-SVG focus asset in the rounded corner, number chip + meta bottom-left

Assets come from the Traits Cyclopedia extractions (icons/, icons_sf/,
icons_svg/ built by the other tools/ extractors) and are bundled as data
URIs into cardface-assets.js.

Usage: python3 build_scanner_v3.py <live_cards.html> <out_html> <out_assets_js>
"""
import sys, os, glob, json, base64, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_trait_poc import b64_outlined, b64_skill_banner


def build_assets(out_js):
    def b64svg_white(f):
        t = open(f).read()
        t = re.sub(r'fill="rgb\([^"]*\)"', 'fill="#fff"', t)
        return 'data:image/svg+xml;base64,' + base64.b64encode(t.encode()).decode()

    def b64svg(f):
        return 'data:image/svg+xml;base64,' + base64.b64encode(open(f, 'rb').read()).decode()

    trait = {os.path.basename(f)[:-4]: b64_outlined(f, os.path.basename(f)[:-4], border=2)
             for f in sorted(glob.glob('icons/*.png'))}
    trait_chip = {os.path.basename(f)[:-4]: b64_outlined(f, os.path.basename(f)[:-4], border=0)
                  for f in sorted(glob.glob('icons/*.png'))}
    skill = {os.path.basename(f)[:-4].replace('skill-', ''): b64_skill_banner(f)
             for f in sorted(glob.glob('icons_sf/skill-*.png'))}
    def b64svg_focus(f):
        # the asset's near-black corner wedge vanishes against the scanner's
        # dark card background; lift it to a readable navy so the icon
        # visibly connects to both card edges like the print
        t = open(f).read().replace('rgb(35,31,32)', '#39416e')
        return 'data:image/svg+xml;base64,' + base64.b64encode(t.encode()).decode()
    focus = {os.path.basename(f)[:-4].replace('focus-', ''): b64svg_focus(f)
             for f in sorted(glob.glob('icons_svg/focus-*.svg'))}
    suit = {os.path.basename(f)[:-4].replace('suit-', ''): b64svg_white(f)
            for f in sorted(glob.glob('icons_svg/suit-*.svg'))}
    js = ('// Card-face assets extracted from the STCC Traits Cyclopedia v2.1 (vector).\n'
          '// Generated by tools/build_scanner_v3.py. Iconography (c) WizKids.\n'
          'const CARDFACE=' + json.dumps({'trait': trait, 'traitChip': trait_chip,
                                          'skill': skill, 'focus': focus, 'suit': suit}) + ';\n')
    open(out_js, 'w').write(js)
    print(f'assets: {len(trait)} traits, {len(skill)} skills, {len(focus)} focus, {len(suit)} suits -> {out_js} ({len(js)//1024} KB)')


CSS = """
/* ===== v3 card-face design (POC port) ===== */
/* capsule outlines everywhere */
.box-pill,.promo-pill,.deck-pill,.suit-pill,.species-pill,.regular-pill,.other-pill,.skill-pill{border-radius:999px;}
.deck-pill{height:22px;box-sizing:border-box;display:inline-flex;align-items:center;padding:0 .8rem;font-size:.76rem;}
/* rulebook chips (trait + suit filters) */
.cardpill{display:inline-flex;align-items:center;gap:.4rem;border-radius:999px;border:none !important;
  height:22px;padding:0 .75rem 0 .1rem;color:#fff;cursor:pointer;user-select:none;
  font-family:'Antonio',sans-serif;font-weight:600;font-size:.86rem;letter-spacing:.03em;
  line-height:1;text-transform:uppercase;background:#556;color:#1a1d26;}
.cardpill img{height:21px;width:21px;}
.cardpill .cnt{font-size:.62rem;font-weight:400;opacity:.75;margin-left:.05rem;}
.cardpill:hover{filter:brightness(1.1);}
.cardpill.active{color:#fff !important;}
.cp-wild.active{color:#20242e !important;}
.cp-species{background:#e2a04a !important;}
.cp-regular{background:#8ec6d8 !important;}
.cp-other{background:#c85340 !important;}
.cp-wild{background:#eef1f6 !important;color:#20242e !important;}
.cp-wild.active{box-shadow:0 0 0 1.5px rgba(32,36,46,.8);}
.suit-pill.suitchip{border:none;color:#1a1d26;padding-left:.55rem;}
.suit-pill.suitchip img{height:13px;width:auto;}
.suit-pill.suitchip.active[data-suit]{background:inherit;}
.skill-pill .cnt{font-size:.6rem;opacity:.8;margin-left:.25rem;}
.skill-pill img{height:13px;width:auto;vertical-align:-2px;margin-right:.3rem;}
.skill-pill{display:inline-flex;align-items:center;}
/* ===== card entries ===== */
.card-entry{border-radius:10px;}
.nb{display:flex;align-items:center;width:fit-content;margin-left:-0.7rem;max-width:calc(100% + .2rem);
  min-height:18px;box-sizing:border-box;padding:.05rem .8rem .05rem .35rem;
  border-radius:0 999px 999px 0;background:#556;
  color:#fff;font-family:'Antonio',sans-serif;font-weight:600;font-size:.74rem;
  letter-spacing:.04em;text-transform:uppercase;line-height:1.15;margin-bottom:.3rem;}
.sb{display:inline-flex;align-items:center;gap:.4rem;align-self:flex-start;margin-left:-0.7rem;
  padding:0 .8rem 0 .3rem;height:18px;box-sizing:border-box;border-radius:0 999px 999px 0;background:#556;
  color:#fff;font-family:'Antonio',sans-serif;font-weight:600;font-size:.66rem;
  letter-spacing:.06em;text-transform:uppercase;margin-bottom:.5rem;}
.sb img{height:.95em;width:auto;}
.skcol{display:flex;flex-direction:column;align-items:flex-start;gap:.3rem;margin-left:-0.7rem;margin-bottom:.35rem;}
.skimg{height:28px;width:auto;}
.ce-traits2{display:flex;flex-direction:row;align-items:flex-start;justify-content:flex-end;gap:0;
  flex:none;max-width:55%;flex-wrap:wrap;}
.vt{display:flex;flex-direction:column;align-items:center;position:relative;margin-left:-4px;}
.vt:first-child{margin-left:0;}
.vt img{width:26px;height:26px;z-index:2;}
.vt-spacer{width:26px;height:5px;}
.vctag{writing-mode:vertical-rl;text-orientation:sideways;display:flex;align-items:center;justify-content:center;
  padding:.65rem 0 .36rem;width:18px;line-height:1;font-family:'Antonio',sans-serif;font-size:.62rem;
  font-weight:600;letter-spacing:.05em;border-radius:0 0 999px 999px;margin-top:-5px;color:#fff;}
.vt img + .vctag{margin-top:-5px;}
.vt .vt-spacer + .vctag{margin-top:0;border-radius:999px;padding-top:.5rem;}
.vt-species{background:#e2a04a;}
.vt-regular{background:#8ec6d8;}
.vt-other{background:#c85340;}
.vt-variable{background:#eef1f6;color:#20242e;}
.focorner{position:absolute;right:-3px;bottom:-3px;height:43px;width:auto;z-index:2;}
.ce-bottom{margin-top:auto;padding-top:.45rem;display:flex;justify-content:space-between;align-items:flex-end;position:relative;z-index:3;}
.cid2{background:#14171f;color:#e8ecf5;display:inline-block;margin-left:-0.7rem;
  font-family:'Antonio',sans-serif;font-size:.56rem;font-weight:600;letter-spacing:.07em;
  padding:.12rem .55rem;border-radius:0 999px 999px 0;box-shadow:inset 0 0 0 1px rgba(255,255,255,.22);}
.cid2 .meta{color:#8a94ac;font-weight:400;margin-left:.35rem;}
"""

NEW_BUILD = """function buildPillCard(c){
  const SUIT_COL={'Person':'#d9bd45','Ally':'#9b6ecf','Ship':'#7a8aaa','Cargo':'#3a6aaa','Location':'#4ac48a','Encounter':'#d4699f','Incident':'#e05a5a','Captain':'#c8a84b','Directive':'#8494ad','Status':'#88aacc'};
  const el=document.createElement('div');
  el.className='card-entry'; el.dataset.suit=c.suit||'';
  const col=SUIT_COL[c.suit]||'#8494ad';
  const sk_=(c.suit||'').toLowerCase();
  const sIcon=CARDFACE.suit[sk_]?'<img src="'+CARDFACE.suit[sk_]+'" alt="">':'';
  const tkey=t=>t.toLowerCase().replace(/['\u2019]/g,'').replace(/\\s+/g,'-');
  const allTags=[...c.species,...c.regular,...c.other].sort((a,b)=>a.length-b.length);
  const vt=allTags.map((t,i)=>{
    let fam=t==='Wildcard'?'variable':c.species.includes(t)?'species':c.other.includes(t)?'other':'regular';
    const ic=CARDFACE.trait[tkey(t)];
    return '<div class="vt" style="z-index:'+(allTags.length-i)+'">'
      +(ic?'<img src="'+ic+'" alt="">':'<span class="vt-spacer"></span>')
      +'<span class="vctag vt-'+fam+(activeTags.has(t)?' match':'')+'">'+t.toUpperCase()+'</span></div>';
  }).join('');
  const skillsHTML=c.skills.filter(s=>!/Focus$/.test(s)).map(s=>{
    const spec=s.split(' ')[0].toLowerCase();
    const src=CARDFACE.skill[spec];
    return src?'<img class="skimg'+(activeSkills.has(s)?' match':'')+'" src="'+src+'" title="'+s+'" alt="">':'';
  }).join('');
  const foci=c.skills.filter(s=>/Focus$/.test(s));
  let corner='';
  if(foci.length){
    const spec=foci[0].split(' ')[0].toLowerCase();
    if(CARDFACE.focus[spec]) corner='<img class="focorner'+(activeSkills.has(foci[0])?' match':'')+'" src="'+CARDFACE.focus[spec]+'" title="'+foci[0]+'" alt="">';
  }
  const badge=badgeInfo(c);
  const strat=hasStrategy(c);
  if(strat){ el.classList.add('has-strategy'); el.onclick=()=>toggleStrategy(c.id); }
  if(openStrategyId===c.id) el.classList.add('drawer-open');
  const stratHTML='';
  const badgeMark=badge?(badge.cls==='update'?'\\u2020':'\\u2022')+' '+badge.text:'';
  let numline='';
  if(c.card_number||badge){
    numline='<div class="ce-bottom"><span class="cid2">'+(c.card_number||'')
      +(badge?(c.card_number?' ':'')+'<span class="meta">'+badgeMark+'</span>':'')+'</span></div>';
  }
  el.innerHTML='<div class="ce-row"><div class="ce-main">'
    +'<div class="nb" style="background:'+col+'">'+c.name+'</div>'
    +'<div class="sb" style="background:'+col+'">'+sIcon+c.suit+'</div>'
    +(skillsHTML?'<div class="skcol">'+skillsHTML+'</div>':'')
    +stratHTML
    +'</div><div class="ce-traits2">'+vt+'</div></div>'
    +numline+corner;
  return el;
}"""

NEW_MAKEPILL = """function makePill(text,cls,kind){
  const p=document.createElement('span');
  let chip=cls==='species-pill'?'cp-species':cls==='other-pill'?'cp-other':'cp-regular';
  if(text==='Wildcard') chip='cp-wild';
  p.className=cls+' cardpill '+chip;
  const ic=CARDFACE.traitChip[text.toLowerCase().replace(/['\u2019]/g,'').replace(/\\s+/g,'-')];
  p.innerHTML=(ic?'<img src="'+ic+'" alt="">':'')+'<span class="lbl">'+displayLabel(text)+'</span><span class="cnt"></span>';
  p.dataset.value=text;
  p.onclick=()=>toggleToken(tokenOf(kind,text));
  return p;
}"""


def patch_html(src, out, assets_js='cardface-assets.js'):
    import hashlib
    ver = hashlib.md5(open(assets_js, 'rb').read()).hexdigest()[:8]
    s = open(src).read()
    # fonts + assets script
    s = s.replace('family=Barlow+Condensed:wght@500;600;700', 'family=Antonio:wght@600')
    s = s.replace('</head>', f'<script src="cardface-assets.js?v={ver}"></script>\n</head>', 1)
    # drop the "New" banner in the header
    s = re.sub(r'<a class="new-banner".*?</a>', '', s, count=1, flags=re.S)
    # preview marker
    s = s.replace('<meta name="viewport" content="width=device-width, initial-scale=1.0">',
                  '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<meta name="robots" content="noindex">', 1)
    s = s.replace('<h1 class="chapter-title"><span>Card</span> Scanner</h1>',
                  '<h1 class="chapter-title"><span>Card</span> Scanner <span style="font-size:.5em;color:#7a8aaa">(card-face preview)</span></h1>')
    # CSS
    s = s.replace('</style>', CSS + '\n</style>', 1)
    # buildPillCard
    s = re.sub(r'function buildPillCard\(c\)\{.*?\n  return el;\n\}', lambda m: NEW_BUILD, s, count=1, flags=re.S)
    # makePill
    s = re.sub(r'function makePill\(text,cls,kind\)\{.*?\n\}', lambda m: NEW_MAKEPILL, s, count=1, flags=re.S)
    # counts iterate direct children only (chips contain inner spans now)
    s = s.replace("const pills=document.getElementById(containerid).querySelectorAll('span');",
                  "const pills=document.getElementById(containerid).querySelectorAll(':scope > span');")
    # counts write into .cnt span
    s = s.replace("pill.textContent=count>0?displayLabel(val)+' ('+count+')':displayLabel(val);",
                  "const cnt=pill.querySelector('.cnt');\n      if(cnt) cnt.textContent=count>0?'('+count+')':'';\n      else pill.textContent=count>0?displayLabel(val)+' ('+count+')':displayLabel(val);")
    # suit pills -> chips
    s = s.replace("""  const p=document.createElement('span');
  p.className='suit-pill'; p.dataset.suit=s; p.textContent=s;""",
"""  const SUIT_COL={'Person':'#d9bd45','Ally':'#9b6ecf','Ship':'#7a8aaa','Cargo':'#3a6aaa','Location':'#4ac48a','Encounter':'#d4699f','Incident':'#e05a5a','Captain':'#c8a84b','Directive':'#8494ad','Status':'#88aacc','Automated Command':'#8494ad'};
  const p=document.createElement('span');
  p.className='suit-pill cardpill suitchip'; p.dataset.suit=s;
  p.style.background=SUIT_COL[s]||'#8494ad';
  const gi=CARDFACE.suit[s.toLowerCase()];
  p.innerHTML=(gi?'<img src="'+gi+'" alt="">':'')+'<span class="lbl">'+s+'</span>';""")
    # skill/focus filter pills: icon + label + count spans
    s = s.replace("p.textContent=t; p.dataset.value=t;",
"""{const m2=t.match(/^(.+)\\s+(Skill|Focus)$/);
  const spec2=m2?m2[1].toLowerCase():'';
  const isF=m2&&m2[2]==='Focus';
  const src=isF?CARDFACE.focus[spec2]:CARDFACE.skill[spec2];
  p.innerHTML=(src?'<img src="'+src+'" alt="">':'')+'<span class="lbl">'+displayLabel(t)+'</span><span class="cnt"></span>';}
  p.dataset.value=t;""")
    open(out, 'w').write(s)
    print('wrote', out, len(s) // 1024, 'KB')


if __name__ == '__main__':
    src, out_html, out_js = sys.argv[1], sys.argv[2], sys.argv[3]
    build_assets(out_js)
    patch_html(src, out_html)
